server:
  port: 8001
  
spring:
  application:
    name: dmsp-eurekaserver
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    ip-address: true
    instance-id: dmsp-eurekaserver
    
    